language: java
install:
  - mkdir __android-sdk__
  - cd __android-sdk__
  - wget -nv http://dl.google.com/android/android-sdk_r22.3-linux.tgz
  - tar -xzf android-sdk_r22.3-linux.tgz
  - export ANDROID_HOME=${PWD}/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  - echo y | android update sdk --filter platform-tools,build-tools-19.1.0,android-18,android-19,addon-google_apis-google-18,extra-android-m2repository --no-ui --force
  - find android-sdk-linux/
  - ldd android-sdk-linux/build-tools/19.1.0/aapt
  - cd ..
  - git clone --depth=1 --branch=sa git://github.com/lp0/robolectric.git __robolectric__
  - cd __robolectric__
  - ./scripts/install-maps-jar.sh
  - ./scripts/install-support-jar.sh
  - mvn -B -V -DskipTests=true install
  - cd ..
  - rm -rf __robolectric__
script:
  - mvn install -DskipTests=true -B -V -X
  - mvn test -B -X
after_script:
  - "[ $TRAVIS_TEST_RESULT -ne 0 ] && head -n 500 target/surefire-reports/*.txt"
